#!/bin/sh

XCODE=`xcode-select -p | awk -F'/' '{print $3}'`

if ls *.xcworkspace >/dev/null 2>&1; then
	echo "Using $XCODE"
	open -a "$XCODE" *.xcworkspace
elif ls *.xcodeproj >/dev/null 2>&1; then
	open -a "$XCODE" *.xcodeproj
	echo "Using $XCODE"
else
	echo "Nothing here"
fi
